// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOedVWfLAXg5UuUQmkS-bCv53es6-lY00',
    appId: '1:892662575098:web:8736a604b44a308317be43',
    messagingSenderId: '892662575098',
    projectId: 'snakeclassic-c2b64',
    authDomain: 'snakeclassic-c2b64.firebaseapp.com',
    storageBucket: 'snakeclassic-c2b64.firebasestorage.app',
    measurementId: 'G-MCV43CW1TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMgAXUXR0w0ZhG65ndyv9nCRfBrBftuU',
    appId: '1:892662575098:android:eb1df6d7837a1f3817be43',
    messagingSenderId: '892662575098',
    projectId: 'snakeclassic-c2b64',
    storageBucket: 'snakeclassic-c2b64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGChdgdnFGIcVBsklt7BCWvunVhh-aTk',
    appId: '1:892662575098:ios:b9e4c65b55e578e617be43',
    messagingSenderId: '892662575098',
    projectId: 'snakeclassic-c2b64',
    storageBucket: 'snakeclassic-c2b64.firebasestorage.app',
    androidClientId: '892662575098-4vsgmgadubaurm2o04pe25anq7r9nhto.apps.googleusercontent.com',
    iosClientId: '892662575098-66vdv6aeni9sj7vsqom1ceh4urafivq4.apps.googleusercontent.com',
    iosBundleId: 'com.retrogames.snakeClassic',
  );

}